import { safeGenerateContent, generateImage, cleanAndParseJSON } from './gemini';
import { Type } from '@google/genai';

export interface GeneratedArticle {
  headline: string;
  deck: string;
  body: string;
  tags: string[];
  suggested_visual_prompt: string;
}

export const agentColumnist = async (topic: string): Promise<GeneratedArticle> => {
  const prompt = `
    You are THE COLUMNIST for MODUS, a high-fashion, accelerationist magazine.
    Topic: "${topic}"
    
    Write a short, punchy, intellectual article about this topic.
    Tone: Haughty, insightful, slightly dystopian, "Vogue meets Wired".
    
    Output JSON only:
    {
      "headline": "A 3-5 word striking title (UPPERCASE)",
      "deck": "A provocative subtitle.",
      "body": "2-3 paragraphs of high-quality prose. Use markdown for emphasis.",
      "tags": ["Tag1", "Tag2"],
      "suggested_visual_prompt": "A detailed description for an AI image generator that captures the mood."
    }
  `;

  const response = await safeGenerateContent({
    model: 'gemini-3-flash-preview',
    contents: prompt,
    config: {
      responseMimeType: 'application/json',
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          headline: { type: Type.STRING },
          deck: { type: Type.STRING },
          body: { type: Type.STRING },
          tags: { type: Type.ARRAY, items: { type: Type.STRING } },
          suggested_visual_prompt: { type: Type.STRING }
        },
        required: ['headline', 'deck', 'body', 'tags', 'suggested_visual_prompt']
      }
    }
  });

  return cleanAndParseJSON(response.text);
};

export const agentPhotographer = async (prompt: string): Promise<string> => {
  // We use the prompt generated by the Columnist directly
  // But we might want to enhance it with "MODUS style" keywords
  const enhancedPrompt = `Editorial fashion photography, ${prompt}, high contrast, grain, 8k resolution, cinematic lighting, avant-garde.`;
  
  return await generateImage(enhancedPrompt, '16:9');
};
