import { safeGenerateContent, generateImage, cleanAndParseJSON, searchTrend } from './gemini';
import { Type } from '@google/genai';

export interface GeneratedArticle {
  headline: string;
  deck: string;
  body: string;
  tags: string[];
  suggested_visual_prompt: string;
}

export const agentScout = async (): Promise<string> => {
  // 1. Search strictly for hard tech trends
  const searchResult = await searchTrend("latest developments in AI models, open-source code repositories, machine learning workflows, and bleeding-edge technology");
  
  // 2. Synthesize a specific, provocative topic from the search results
  const prompt = `
    You are THE SCOUT for MODUS. Your job is to find a single, highly specific hard-tech topic for our next article based on current real-world signals.
    
    CRITICAL RULE: Focus ONLY on technology (AI models, code, workflows, hardware). Ignore fashion, culture, and social issues entirely at this stage. We need the raw technical foundation.
    
    Here is the raw data from the live web:
    ${searchResult.text}
    
    Synthesize this into a SINGLE, punchy topic phrase (max 5-7 words).
    Examples: "The Rise of Local LLMs", "ComfyUI Node Architectures", "Synthetic Data Generation".
    
    Output ONLY the topic phrase, nothing else.
  `;

  const response = await safeGenerateContent({
    model: 'gemini-3-flash-preview',
    contents: prompt
  });

  return response.text?.trim() || "Local LLM Orchestration";
};

export const agentTargetedSearch = async (topic: string): Promise<string> => {
  // Deep dive into a specific topic
  const searchResult = await searchTrend(`latest technical details and developments regarding: ${topic}`);
  
  const prompt = `
    You are THE SCOUT. The Editor has requested a deep-dive on the following topic: "${topic}".
    
    Review the live web data below and extract the most crucial, cutting-edge technical facts, context, and recent developments.
    
    Raw Data:
    ${searchResult.text}
    
    Provide a concise, highly technical briefing (max 3 sentences) that will serve as the foundation for the Columnist.
  `;

  const response = await safeGenerateContent({
    model: 'gemini-3-flash-preview',
    contents: prompt
  });

  return response.text?.trim() || `Deep dive context for ${topic} acquired.`;
};

export const agentColumnist = async (topic: string, context: string, lens: string, wordCountTarget: string): Promise<GeneratedArticle> => {
  let lengthInstruction = "2-3 paragraphs";
  if (wordCountTarget.includes("300")) lengthInstruction = "1-2 short, punchy paragraphs";
  if (wordCountTarget.includes("1200")) lengthInstruction = "4-5 detailed paragraphs";

  const prompt = `
    You are THE COLUMNIST for MODUS, a high-fashion, accelerationist magazine.
    
    Base Topic (The Tech Foundation): "${topic}"
    Context/Briefing: "${context}"
    
    Your task is to write an article about this technical topic, but you MUST apply the following Editorial Lens: "${lens}".
    This means you must view the hard technology through the perspective of ${lens}.
    
    Tone: Intellectual, haughty, insightful, "Vogue meets Wired".
    Length: ${lengthInstruction}.
    
    Output JSON only:
    {
      "headline": "A 3-5 word striking title (UPPERCASE)",
      "deck": "A provocative subtitle.",
      "body": "The main prose. Use markdown for emphasis.",
      "tags": ["Tag1", "Tag2"],
      "suggested_visual_prompt": "A detailed description for an AI image generator that captures the mood."
    }
  `;

  const response = await safeGenerateContent({
    model: 'gemini-3-flash-preview',
    contents: prompt,
    config: {
      responseMimeType: 'application/json',
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          headline: { type: Type.STRING },
          deck: { type: Type.STRING },
          body: { type: Type.STRING },
          tags: { type: Type.ARRAY, items: { type: Type.STRING } },
          suggested_visual_prompt: { type: Type.STRING }
        },
        required: ['headline', 'deck', 'body', 'tags', 'suggested_visual_prompt']
      }
    }
  });

  return cleanAndParseJSON(response.text);
};

export const agentPhotographer = async (prompt: string, visualStyle: string, aspectRatio: string): Promise<string> => {
  // We use the prompt generated by the Columnist and enhance it with the selected visual style
  const styleMap: Record<string, string> = {
    'Editorial Photography': 'high-end editorial fashion photography, 35mm film, studio lighting, Vogue cover style',
    'Cyberpunk Render': 'cyberpunk aesthetic, neon lighting, octane render, unreal engine 5, highly detailed 3d',
    'Technical Blueprint': 'architectural blueprint style, technical drawing, wireframe, schematic, minimalist lines',
    'Abstract Latent': 'abstract latent space visualization, fluid dynamics, glitch art, surreal digital noise'
  };
  
  const stylePrompt = styleMap[visualStyle] || styleMap['Editorial Photography'];
  const enhancedPrompt = `${stylePrompt}, ${prompt}, 8k resolution, masterpiece.`;
  
  return await generateImage(enhancedPrompt, aspectRatio);
};
