import React from 'react';
import { RecipeArtifact } from '../types';
import { AtelierRecipe } from './ui/Tools';

interface RecipeSectionProps {
  recipes: RecipeArtifact[];
}

export const RecipeSection: React.FC<RecipeSectionProps> = ({ recipes }) => {
  if (!recipes || recipes.length === 0) return null;

  return (
    <section className="bg-neutral-50 border-t border-black py-32">
      <div className="max-w-[1536px] mx-auto px-6 md:px-16">
        <div className="flex flex-col md:flex-row justify-between items-end mb-24 border-b border-neutral-200 pb-8">
          <div className="max-w-2xl">
             <span className="block text-xs font-sans font-bold tracking-[0.25em] uppercase mb-6 text-neutral-400">The Atelier</span>
             <h3 className="font-display text-6xl md:text-7xl leading-none mb-6">Technical Schematics</h3>
             <p className="font-sans text-base text-neutral-500 max-w-lg leading-relaxed">
               Reproducible workflows generated by the Engineering Agent. 
               Use these parameters to recreate the visual assets found in this issue.
             </p>
          </div>
          <div className="text-xs font-sans font-bold tracking-[0.2em] uppercase mt-8 md:mt-0 text-black">
            Open Source • V1.0
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-12">
          {recipes.map((recipe) => (
            <div key={recipe.id} className="bg-white shadow-sm hover:shadow-xl transition-all duration-500 transform hover:-translate-y-2">
               <AtelierRecipe data={recipe} className="h-full border-0" />
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};